apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercars-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supercars
  template:
    metadata:
      labels:
        app: supercars
    spec:
      containers:
      - name: supercars
        image: supercars:latest
        ports:
        - containerPort: 8080
