apiVersion: apps/v1
kind: Deployment
metadata:
  name: supercars-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supercars
  template:
    metadata:
      labels:
        app: supercars
    spec:
      containers:
        - name: supercar-container
          image: rahulv1996/supercars:latest
          ports:
            - containerPort: 8080
